

// Generated by https://quicktype.io

export interface ILinkRest{
    msg:  string;
    data: Data[];
}

export interface ILinkRestObj{
    msg:  string;
    data: Data;
}

export interface Data {
    name:  string;
    link:  string;
    start: string;
    id:    string;
}

export interface DataSend {
    name:  string;
    link:  string;
    start: number;
    id?:string;
}
